// Actual upstream recipient selection with an isolated AstrBot cfg and fake transport.
import assert from 'node:assert/strict';
import fs from 'node:fs';
const worker=fs.readFileSync(new URL('../engine/worker.mjs',import.meta.url),'utf8');
const hook=worker.match(/^globalThis\.cfg=.*;$/m)?.[0];
assert.ok(hook,'Worker must expose this bot namespace to the upstream master selector');
const initialize=new Function('initial',hook);
globalThis.logger={warn:()=>{}};
let settings={masterNotify:[]};
globalThis.__masterConfig={getDefOrConfig:()=>settings};
let source=fs.readFileSync(new URL('../engine/upstream/utils/masterMsg.js',import.meta.url),'utf8');
source=source.replace("import { Config } from '#components'",'const Config=globalThis.__masterConfig;');
const {resolveMasterTargets,sendMaster}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const sent=[];
globalThis.Bot={uin:'bot-one',pickFriend:id=>({sendMsg:async message=>{sent.push({id,message});return {message_id:'mock'};}}),sendMasterMsg:()=>{throw Error('Broadcast forbidden');}};
initialize({self_id:'bot-one',admins:['owner-one','owner-two','owner-one']});
assert.deepEqual(resolveMasterTargets(),['owner-one']);
assert.equal(await sendMaster('fixture'),true);
assert.deepEqual(sent.map(x=>x.id),['owner-one']);
settings={masterNotify:['owner-two','stranger']};
assert.deepEqual(resolveMasterTargets(),['owner-two']);
await sendMaster('fixture');
assert.deepEqual(sent.map(x=>x.id),['owner-one','owner-two']);
settings={masterNotify:['stranger']};
assert.deepEqual(resolveMasterTargets(),['owner-one']);
initialize({self_id:'bot-two',admins:['other-owner']});
assert.deepEqual(resolveMasterTargets(),['other-owner']);
Bot.pickFriend=()=>({sendMsg:async()=>({error:'mock-failure'})});
assert.equal(await sendMaster('fixture'),false);
console.log('Master recipient selection, namespace isolation and delivery failures: 9 checks passed');
